apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  labels:
    app: argo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-stage-demo
  template:
    metadata:
      labels:
        app: sc-stage-demo
    spec:
      containers:
      - name: sc-stage-demo
        image: m95kandan/website
        ports:
        - containerPort: 80
