apiVersion: v1
kind: Service
metadata:
  name: agro-app
spec:
  selector:
    name: sc-stage-demo
  ports:
  - name: sc-stage-svc
    protocol: TCP
    port: 81
    targetPort: 8081
  type: NodePort  
